{'name': 'Web Enterprise',
 'category': 'Hidden',
 'version': '1.0',
 'description': '\n'
                'Odoo Enterprise Web Client.\n'
                '===========================\n'
                '\n'
                'This module modifies the web addon to provide Enterprise design_omeer and responsiveness.\n'
                '        ',
 'depends': ['web', 'base_setup'],
 'auto_install': ['web'],
 'data': ['views/webclient_templates.xml', 'views/res_users_views.xml'],
 'assets': {'web._assets_primary_variables': [('after',
                                               'web/static/src/scss/primary_variables.scss',
                                               'web_enterprise_omeer/static/src/**/*.variables.scss'),
                                              ('before',
                                               'web/static/src/scss/primary_variables.scss',
                                               'web_enterprise_omeer/static/src/scss/primary_variables.scss')],
            'web._assets_secondary_variables': [('before',
                                                 'web/static/src/scss/secondary_variables.scss',
                                                 'web_enterprise_omeer/static/src/scss/secondary_variables.scss')],
            'web._assets_backend_helpers': [('before',
                                             'web/static/src/scss/bootstrap_overridden.scss',
                                             'web_enterprise_omeer/static/src/scss/bootstrap_overridden.scss')],
            'web.assets_frontend': ['web_enterprise_omeer/static/src/webclient/home_menu/home_menu_background.scss',
                                    'web_enterprise_omeer/static/src/webclient/navbar/navbar.scss'],
            'web.assets_backend': ['web_enterprise_omeer/static/src/webclient/**/*.scss',
                                   'web_enterprise_omeer/static/src/views/**/*.scss',
                                   'web_enterprise_omeer/static/src/core/**/*',
                                   'web_enterprise_omeer/static/src/webclient/**/*.js',
                                   ('after',
                                    'web/static/src/views/list/list_renderer.xml',
                                    'web_enterprise_omeer/static/src/views/list/list_renderer_desktop.xml'),
                                   'web_enterprise_omeer/static/src/webclient/**/*.xml',
                                   'web_enterprise_omeer/static/src/views/**/*.js',
                                   'web_enterprise_omeer/static/src/views/**/*.xml',
                                   ('remove', 'web_enterprise_omeer/static/src/views/pivot/**'),
                                   ('remove', 'web_enterprise_omeer/static/src/webclient/home_menu/expiration_panel.*'),
                                   ('remove', 'web_enterprise_omeer/static/src/**/*.dark.scss')],
            'web.assets_backend_lazy': ['web_enterprise_omeer/static/src/views/pivot/**'],
            'web.assets_backend_lazy_dark': [('include', 'web.dark_mode_variables'),
                                             ('before',
                                              'web_enterprise_omeer/static/src/scss/bootstrap_overridden.scss',
                                              'web_enterprise_omeer/static/src/scss/bootstrap_overridden.dark.scss'),
                                             ('after',
                                              'web/static/lib/bootstrap/scss/_functions.scss',
                                              'web_enterprise_omeer/static/src/scss/bs_functions_overridden.dark.scss')],
            'web.assets_web': [('replace', 'web/static/src/main.js', 'web_enterprise_omeer/static/src/main.js')],
            'web.dark_mode_variables': [('before',
                                         'web_enterprise_omeer/static/src/scss/primary_variables.scss',
                                         'web_enterprise_omeer/static/src/scss/primary_variables.dark.scss'),
                                        ('before',
                                         'web_enterprise_omeer/static/src/**/*.variables.scss',
                                         'web_enterprise_omeer/static/src/**/*.variables.dark.scss'),
                                        ('before',
                                         'web_enterprise_omeer/static/src/scss/secondary_variables.scss',
                                         'web_enterprise_omeer/static/src/scss/secondary_variables.dark.scss')],
            'web.assets_web_dark': [('include', 'web.dark_mode_variables'),
                                    ('before',
                                     'web_enterprise_omeer/static/src/scss/bootstrap_overridden.scss',
                                     'web_enterprise_omeer/static/src/scss/bootstrap_overridden.dark.scss'),
                                    ('after',
                                     'web/static/lib/bootstrap/scss/_functions.scss',
                                     'web_enterprise_omeer/static/src/scss/bs_functions_overridden.dark.scss'),
                                    'web_enterprise_omeer/static/src/**/*.dark.scss'],
            'web.tests_assets': ['web_enterprise_omeer/static/tests/*.js'],
            'web.assets_tests': ['web_enterprise_omeer/static/tests/tours/**/*.js'],
            'web.assets_unit_tests': ['web_enterprise_omeer/static/tests/**/*.test.js',
                                      ('remove',
                                       'web_enterprise_omeer/static/tests/webclient/expiration_panel.test.js')],
            'web.qunit_suite_tests': ['web_enterprise_omeer/static/tests/views/**/*.js',
                                      'web_enterprise_omeer/static/tests/webclient/**/*.js',
                                      ('remove', 'web_enterprise_omeer/static/tests/**/*.test.js'),
                                      ('remove',
                                       'web_enterprise_omeer/static/tests/webclient/expiration_panel.test.js')]},
 'author': 'Ahmed Omeer',
 'license': 'LGPL-3',
 'website': 'https://www.facebook.com/ahmedomeerstark'}
